---
- hosts: localhost
  connection: local
  become: true

  vars_files: 
    - main.yml

  tasks:

  - name: NEOVIM BUILD - install dependencies for neovim.
    apt:
      name: "{{ depends }}"
      state: latest
      update_cache: true
      cache_valid_time: 3600
    when: ansible_os_family == "Debian" 

  - name: NEOVIM BUILD - Make sure that the neovim-runtime package from apt is not installed.
    apt:
      name: neovim-runtime
      state: absent
    when: ansible_os_family == "Debian" 
    

  - name: NEOVIM BUILD - get versions of all installed packages. 
    package_facts:
      manager: auto 

  - name: NEOVIM BUILD - Set Neovim's version number to variable. 
    set_fact:
      neovim_version: "{{ ansible_facts.packages['neovim']|
                          map(attribute='version')|
                          list }}" 
    when: "'neovim' in ansible_facts.packages"

  - name: NEOVIM BUILD - Cleanup - check to see if the neovim directory has already been cloned.
    stat:
      path: "/home/{{ username }}/neovim"
    register: cloned

  - name: NEOVIM BUILD - cleanup - remove neovim directory if it exists.
    file:
      path: "/home/{{ username }}/neovim"
      state: absent
    when: cloned.stat.exists

  - block: 

    - name: NEOVIM BUILD - clone the neovim repo.
      git:
        repo: https://github.com/neovim/neovim
        dest: "/home/{{ username }}/neovim"

    - name: NEOVIM BUILD - run build commands.
      shell: | 
        cd /home/{{ username }}/neovim
        git checkout stable
        make CMAKE_BUILD_TYPE=RelWithDebInfo
        cd build && cpack -G DEB && sudo dpkg -i nvim-linux64.deb
    when: neovim_version is undefined or neovim_version != neovim_current
