#!/bin/bash
# Wrapper script to handle certain actions in Newsboat.
# Supports WSL (Windows), macOS, and Linux (Wayland only).

if [[ $(grep -i microsoft /proc/version 2>/dev/null) ]]; then
  # WSL / Windows
  BROWSER='/mnt/c/Program Files/Browser Tamer/bt.exe'
  CLIPBOARD_UTILITY=('wl-copy')
elif [[ "$OSTYPE" == "darwin"* ]]; then
  # macOS
  BROWSER='open'
  CLIPBOARD_UTILITY=('pbcopy')
  IMG_UTILITY='open'
else
  # Linux / Wayland (Sway)
  BROWSER='firefox'
  CLIPBOARD_UTILITY=('wl-copy')
  IMG_UTILITY='swayimg'
fi

# If the first argument doesn't exist then there's nothing to do.
if [[ -z "$1" ]]; then
  exit 13
fi

# Check to see if this is being invoked by my clipboard macro in Newsboat.
if [[ "$2" = "clip" ]]; then
  echo -n "$1" | "${CLIPBOARD_UTILITY[@]}"
  exit 0
fi

# If we're not copying something to the clipboard, what are we doing?
case "$1" in
  http://*|https://*)
    if [[ "$OSTYPE" == "darwin"* ]]; then
      "$BROWSER" "$1"
    else
      "$BROWSER" "$1"
    fi
    ;;
  *png|*jpg|*jpe|*jpeg|*gif)
    "$IMG_UTILITY" "$1"
    ;;
  *)
    if [ -f "$1" ]; then "$EDITOR" "$1"
    else open "$1" >/dev/null 2>&1
    fi
    ;;
esac
